-- Migration 019: Interest list (V1 — DB capture only, no email yet)
--
-- Captures community-interest signups from the public /interest form.
-- V2 will add Resend integration and populate `resend_contact_id` after
-- pushing each new contact to the Resend audience. Schema is unchanged
-- between V1 and V2; only the application-side code differs.

CREATE TABLE interests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  name TEXT,
  source_path TEXT,
  interests TEXT[] NOT NULL DEFAULT '{}',     -- ['membership','day_pass','events','telegram']
  resend_contact_id TEXT,                      -- populated by V2 Resend sync
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_interests_email ON interests (email);

ALTER TABLE interests ENABLE ROW LEVEL SECURITY;

-- The public form posts via the server-side API route using the service-role
-- client (bypasses RLS), so anon doesn't need INSERT here. RLS enforces:
-- only admin members can read the list.
CREATE POLICY "admins_all" ON interests
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM members
      WHERE supabase_user_id = auth.uid() AND is_admin = true
    )
  );
