name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Remove PR preview directory
        run: |
          if [ -d "pr-${{ github.event.pull_request.number }}" ]; then
            git rm -rf pr-${{ github.event.pull_request.number }}
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "Remove preview for PR #${{ github.event.pull_request.number }}"
            git push
          fi
