name: Deploy PR Preview

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm install
      - run: pnpm build
        env:
          VITE_BASE_URL: /regenhub.xyz/pr-${{ github.event.pull_request.number }}/
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: pr-${{ github.event.pull_request.number }}
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview
          message: |
            Preview: https://regenhub-boulder.github.io/regenhub.xyz/pr-${{ github.event.pull_request.number }}/
